### ISSUE TITLE
Misleading responses to impossible actions

### ISSUE THREAD

**Issue by toriningen** [i7/counterfeit-monkey#103]
>use gel on remover
    Since the S-remover contains something useful, it might be a 
    bad idea to change its form. We might not be able to 
    get the contents back.

I suppose it's incorrect to say that remover "contains" anything. Even if it does (I haven't completed the game yet, so if it does, it's kind of a spoiler. Does it?..), I believe that using gel should either say "nothing happens" or maybe say something about valuable equipment you can't risk by exposing to untested substances.

    >use gel on gel
    We dip out pea-sized quantity of gel and rub it gently 
    onto the restoration gel. Alas, nothing happens.

I cannot imagine this process. Should it be possible?

P.S. Side question — is it okay for me to spam with issues like this (e.g. one issue per each noticed problem), or is it better to aggregate all observations into a single issue, or even refrain from posting issues about these things?

**Comment by angstsmurf** [comment]
I think the first one is fixed in [the current version](https://www.dropbox.com/s/lcuor07lkn3salj/CM_rel7beta2D.gblorb?dl=0).

It is definitely okay to keep spamming with these issues! Thanks a lot! Several issues per bug report is generally frowned upon, but I don't really mind if you prefer it that way. It is not like we are drowning in reports and activity on this repository.

**Comment by angstsmurf** [comment]
And bc72567 should take care of the second one. Feel free to come up with better responses.

**Comment by toriningen** [comment]
For me these look perfect. Thank you, I am closing this then.
