### ISSUE TITLE
Tap description varies between inspections

### ISSUE THREAD

**Issue by toriningen** [i7/counterfeit-monkey#106]
If you obtain tap somehow (e.g. from pastis, for example), and then inspect it, it will change its color/type each time you look at it. I am not sure whether it shouldn't remember its type and determine whether it's hot or cold at the time of being obtained or observed for the first time:

    >x tap
    It's a tap marked Cold, though not screwed into any sort of plumbing fixture at the moment.
    
    The tap is currently switched on.
      
    >x tap
    It's a tap marked Hot, though not screwed into any sort of plumbing fixture at the moment.
     
    The tap is currently switched on.

**Comment by angstsmurf** [comment]
I think this is because taps were originally always part of a sink, and it was intentionally left vague how many taps the sink actually had, to avoid the needless complication of implementing a hot and a cold tap on every sink and trying to make the parser tell them apart. Now I have given them a permanent temperature instead, although they seem to be cold most of the time for some reason. (309bac3)

I also noticed plenty of places in the code where it was still assumed that taps are connected to something. This should be fixed with 3baa3a6.

**Comment by angstsmurf** [comment]
Unless you have any more questions, I'll close this as fixed. Thanks for reporting this!
