### ISSUE TITLE
Homonym paddle on activist's sign

### ISSUE THREAD

**Issue by dbbnrl** [i7/counterfeit-monkey#108]
Playing release 7:

 - Show the activist's sign ("TOXI WASTE AWARENESS!") to the bartender.
 - You now have a different sign (the protesters' sign on "NON-REFERRABLE PROCEDURES").
 - First of all, this doesn't make sense as a homonym-swap, as both objects are signs in the same sense.
 - Secondly, you're stuck with the new sign.  Any attempt to interact with it other than looking yields "The sign is out of reach".  So you can't, for instance, use the gel to change it back.

**Comment by angstsmurf** [comment]
Fixed in a17006e. This was triggered by the protest sign entering the repository when it is diminished by the All-purpose Officer. I need to check if there are other kinds of object with identical printed names but different descriptions -- that would cause the same kind of problem elsewhere.

Note that we still allow the homonym paddle to switch between different kinds of tarot cards, so it is not strictly homonyms only.
