### ISSUE TITLE
Homonym paddle on pit

### ISSUE THREAD

**Issue by dbbnrl** [i7/counterfeit-monkey#109]
Playing release 7:

  - Remove 'a' from pita, yielding a pit.  ("The hard center of a fruit...")
  - Show pit to bartender.  She transforms it into... the exact same pit?

**Comment by angstsmurf** [comment]
This probably happened in the conversion to Inform 6M62, due to the new text handling introduced in 6L38. 

The description of the pit includes conditional text: it will say "center of a fruit" or "centre of a fruit" depending on whether the player wears the Britishizing goggles, and this makes the condition "if the description of the item is not the description of the target" true, i.e. Inform thinks that the identical descriptions are in fact different, and that the pit and the pit are two different kinds of object.

Fortunately this is easy to fix. Fixing this seems to take care of #108 as well, though I don't quite understand why.

**Comment by angstsmurf** [comment]
Fixed in 2275fba. This is actually reported as Inform bugs [0001968](http://inform7.com/mantis/view.php?id=1968) and [0001865.](http://inform7.com/mantis/view.php?id=1865)
