### ISSUE TITLE
Stuck in teenagers/roundabout scene

### ISSUE THREAD

**Issue by dbbnrl** [i7/counterfeit-monkey#113]
Playing release 7:

The first time I played the game, I dithered around looking at descriptions and generally not picking up the rifle for too long.  Once the officer climbs back down and picks the rifle back up, I found that I was completely stuck:  I can't leave, because traffic is still not moving.  I can't solve the puzzle, because I can't get the rifle.  The officer, the teens, and I just hang around in roundabout limbo forever... at least as far as I can figure out.

The only way I was able to escape was by restoring from a save (unfortunately I saved just after getting out of the car, so I had to restart the game).

Would it make sense to add the following script:  If the officer picks up the rifle, and the teens are still present, the officer should notice you've been lurking around for awhile and nab you.

The only problem with that is that if it ends the game, the undo feature will put us in a different kind of infinite loop, where you undo to a point where it is still too late to actually solve anything.  I don't know how to get around that, unless it's possible to suppress the bad-ending-undo-last-turn feature for this case?  The player might still have to restart or restore, but at least they won't be frustrated stuck in a loop, not knowing if there's a way to get out.

Alternatively, maybe it would make sense for the officer to climb down, pick up the rifle, and then take the teenagers into custody?  That would end the scene in failure, but that's OK -- there is already a worse failure option in that scene.  And dragging the teenagers off to jail seems like the logical thing for him to do after he finishes with the statue.

**Comment by angstsmurf** [comment]
Thanks for reporting this!

In 8ef4f7d, I tried to make sure that this scene is always winnable by o-removing the olive branch. Before, the officer would just shoot the resulting live branch with the rifle, but after that commit, he would drop the rifle again and start climbing the statue, giving the player another chance at stealing the rifle.

This could definitely do with a nudge or two to help the player realise that this is actually the only way forward, and there is still something weird about how the scene just seems to freeze at that moment until you mess with the branch.

Now that I think about it, it makes more sense to make the irritation count variable increase even if we do nothing, so that the scene ends with the depluralization of the crowd. Or with the capture of the teenagers, as you say, but that would require more work.

**Comment by angstsmurf** [comment]
Improved this a little with 949b420. It adds a message about how "[o]ne of [the teenagers] glances at our letter-remover and then at the olive branch", and now the irritation reactions of the All-purpose Officer will advance even if we just wait (one advancement every ten turns). This is not ideal, as those irritation messages don't make a lot of sense unless we have done something to annoy him. I suppose we really ought to create an alternative series of "spontaneous annoyances", protesters throwing things at him etc.

**Comment by angstsmurf** [comment]
I have compiled a new debug version of the game together with some save files, which should make it easy to test my fixes to the issues you reported. You are welcome to try it out!
https://www.dropbox.com/s/kiftyhpx8tfqnzg/MonkeyAndSaves.zip?dl=0

**Comment by angstsmurf** [comment]
I guess we can consider this resolved.

**Comment by dbbnrl** [comment]
My apologies if you were waiting for me -- I haven't had an opportunity to play for a while.  I will give it a try tonight if I can.

**Comment by angstsmurf** [comment]
Hey, no rush! My apologies if I came off as impatient. I just don't like to keep these issues open longer than necessary. Or, to put it another way, I like closing them :)
