### ISSUE TITLE
Massive pug

### ISSUE THREAD

**Issue by dbbnrl** [i7/counterfeit-monkey#114]
Playing release 7:

The power cord has a massive plug at each end.  I attempted to remove the L, because I really want a massive pug.  I got the usual failure about "too tightly bound to its modifiers", but does this really apply when the end result is sensible?

**Comment by angstsmurf** [comment]
There are a number of those throughout the game -- words bound to modifiers that still make sense, but which we are not allowed to make. I've been pondering a good way to deal with "ink tap" or "sink rain," for example. Please let us know if you find any others!

**Comment by angstsmurf** [comment]
Let me know if you can think of any improvements to [the description of the pug](https://github.com/i7/counterfeit-monkey/blob/5be782dfc0e66228785b452cfc6c589d8d2f8abd/Counterfeit%20Monkey.materials/Extensions/Counterfeit%20Monkey/Repository%20Alphabetic%20Details.i7x#L2524). Perhaps it should eat the player rather than crushing them?
