### ISSUE TITLE
"L R-REMOVER" in all caps does not work

### ISSUE THREAD

**Issue by michaelgundlach** [i7/counterfeit-monkey#116]
The first time the game suggests that you look at the r-remover, typing in caps
`L R-REMOVER`
says it doesn't know what we're talking about.  Typing
`l r-remover`
works fine.

**Comment by angstsmurf** [comment]
Thanks for reporting this!

The culprit seems to be [this line in Tools.i7x](https://github.com/i7/counterfeit-monkey/blob/master/Counterfeit%20Monkey.materials/Extensions/Counterfeit%20Monkey/Tools.i7x#L102):
`replace the text " [current setting of the letter-remover]-remover" in N with " letter-remover";
`

I've always assumed that this kind of comparison is case-insensitive, and there is plenty of code in the game that seems to assume that, but apparently it is not.

This can be fixed by adding a First after reading a command rule that changes the text of the player's command to "[the player's command in lower case]", i.e. always converting the player input to lower case. I'll need to check how much slower this makes things, though.

**Comment by angstsmurf** [comment]
Fixed by 937902b.
