### ISSUE TITLE
Created objects don't lose attributes when destroyed

### ISSUE THREAD

**Issue by sukiletxe** [i7/counterfeit-monkey#134]
Maybe unimportant (you judge) but weird behaviour, at least for me. If I do preamps > reams > ream > put paste of ream at bookstore, then when I do cream > ream on fridge at graduate student office the ream has paste on it.

I don't know if this is intentional or not: logic tells me it's not, but the "The cream gives way to the now familiar ream" statement tells me it may as well be.

**Comment by angstsmurf** [comment]
Thanks for reporting this! That should definitely not happen. I'll have a look.

**Comment by angstsmurf** [comment]
The cause of this is obvious in the source. It is [mentioned](https://github.com/i7/counterfeit-monkey/blob/master/Counterfeit%20Monkey.materials/Extensions/Counterfeit%20Monkey/Act%20II%20Among%20Smugglers.i7x#L107) [twice](https://github.com/i7/counterfeit-monkey/blob/master/Counterfeit%20Monkey.materials/Extensions/Counterfeit%20Monkey/Repository%20Major%20Contents.i7x#L596)  that we cheat and reuse the single ream object.

Usually, when an identical thing can be created in two different ways, we have two separate but identical objects. This can be a bit of work to implement, though, as we have to create a new kind of object and make sure that we always refer to the kind rather than the individual instances in the source code. There are also some cases where kinds can't be used at all, such as in lists.

In this particular case we can avoid all that, as the ream is removed entirely from the game after the bookstore, and there is no way to acquire the cream until after the bookstore scene. However, we must remember to remove all telltale signs that the new ream is in fact the one and same, so we reset all relevant properties in 3ec5a4e.

A nice detail is that the description of the ream changes when we create it from the cream. It is then said to have "an attractive milky color" rather than "white-white".
