### ISSUE TITLE
Glulxe fatal error when making “louse”

### ISSUE THREAD

**Issue by jackk225** [i7/counterfeit-monkey#139]
B-removing the “blouse” in the Hostel yields a description of the attendant running away, and then the following error message:
“Glulxe fatal error: Memory write to read-only address (1C)”
Then my interpreter crashed.

I certainly deserve to be punished for that despicable action, but it’s probably worth noting anyway!

**Comment by angstsmurf** [comment]
Thanks for reporting this!

It is caused by the code that makes created creatures spontaneously exit any container, including the repository, which is an abstract off-stage container where we keep everything the player can make. I'm surprised this hasn't caused a lot more trouble. 7569bc8 should take care of it.
