### ISSUE TITLE
Strange disambiguation error with password

### ISSUE THREAD

**Issue by angstsmurf** [i7/counterfeit-monkey#15]
I've been comparing the transcript from typing TEST ME in the 6G60 version with transcripts from the latest version. There are plenty of differences, mainly due to randomized messages, but the last one that actually seems like a genuine bug is this.

6G60 transcript:
>[307] x password
Under the influence of the reclamation computer, the password has settled down and now reads "4tsaj39nbtz".

6M62 transcript:
>[307] x password
That noun did not make sense in this context.

The parser fails to disambiguate between the password-thing carried by the player and the password security program running on the reclamation computer, but gives a nonsense error message instead of a disambiguation choice.

None of the "Does the player mean" rules I've tried has any effect on this. Likely this has something to do with the Numbered Disambiguation Choices or Smarter Parser extensions. Or possibly Computers.

It also might be connected [to this](https://github.com/i7/counterfeit-monkey/commit/023a94a8955de0857deaf8d6506b018049e0a6eb).

EDIT: I've made a test called password-bug for this.

With Trace turned on, we get on one line:
```
The password (6264013) in ourselves : 2176 points
  [token resulted in failure with error type 8]
```

What might this mean?

**Comment by vlaviano** [comment]
Error type 8 is MULTI_PE. (PE stands for parser error.) It occurs when the parser is trying to match a grammar token that can't represent multiple objects against input text that represents multiple objects and produces an error message like "You can't use multiple objects with that verb".

"That noun does not make sense in this context" is for error 19, NOTINCONTEXT_PE. The parser code sometimes replaces one etype with another before an error is reported to the player. More trace output (at level 5) would help us to understand what exactly is going on.

**Comment by angstsmurf** [comment]
This might be overkill, but here is the result with [trace 10](https://gist.github.com/angstsmurf/719d34fa6aebc454aa353b6322c78a28).

**Comment by vlaviano** [comment]
By default, examine has a single grammar line:
```
Verb 'examine' 'x//' 'watch' 'describe' 'check'
    * noun  -> Examine
;
```
This trace shows that Counterfeit Monkey has 5 grammar lines for examine:
```
  * 'indoors' -> A242_checking_indoors
  * scope=Routine(2119375) -> A123_local_looking
  * noun -> Examine
  * 'repositor' 'descripti' -> A243_checking_repository_des
  * noun 'with' / 'through' held -> A197_looking_at_it_through
```
The extra four are introduced by the following bits of source code:
```
Understand "check indoors" as checking indoors.
Checking indoors is an action out of world.

Understand "examine [any locally-present room]" [...] as local looking.

Understand "check repository descriptions" as checking repository descriptions.
Checking repository descriptions is an action out of world.

Understand "examine [something] with/through [something preferably held]" as
looking at it through.
```
I think that the two "check" meta verbs are grouped with examine because, by default, "check" is a synonym for "examine" and there's no 'Understand "check" as something new' statement.

In the presence of multiple grammar lines, the parser tries each one in turn until one succeeds or until they all fail. If they all fail, the "best" error message is reported to the player, where best is defined as most-specific (i.e., the highest error number).

The trace shows us that all lines fail, with the following errors:
line 0: line rejected for not ending with correct preposition ('indoors') (this is error 1, STUCK_PE)
line 1: token resulted in failure with error type 18 (ASKSCOPE_PE)
line 2: token resulted in failure with error type 8 (MULTI_PE)
line 3: line rejected for not ending with correct preposition ('repository' 'description') (STUCK_PE)
line 4: token resulted in failure with error type 8 (MULTI_PE)

So, we'd expect the error message to come from line 1, since 18 is greater than 8 or 1 and is considered "the most specific error." The ASKSCOPE_PE error is a bit unusual. It means that a token with an associated scope routine has failed and the routine is to be called and given a chance to produce whatever error it wants. If it doesn't want to, the parser maintains a "next best error" that it will produce instead.

In this case, the I6-level scope=Routine(2119375) token is associated with [any locally-present room] in the I7 code. My experiments show that I7-generated scope routines produce NOTINCONTEXT_PE as an error when asked (when called with scope_stage = 3), so this explains why we see the "That noun did not make sense in this context" error message. (See §31 and §32 of the DM4 for more on scope tokens and scope_stage.)

However, that error message is misleading, because the wrong grammar line "won", and it's really line 2 that we'd expect to match "examine password". That's where we need to focus our attention.

To be continued...

**Comment by angstsmurf** [comment]
That's interesting. I had a similar issue in the Arbot Maps & Antiques shop, where the parser insisted on examining the room rather than the map collection. There I just hacked around it with an Instead rule while peeking into the player's command.

**Comment by vlaviano** [comment]
angstsmurf wrote:
> There are plenty of differences, mainly due to randomized messages

Check out §8.18. You can add something like:
```
When play begins, seed the random-number generator with 1234.
```
and you should get the same sequence of pseudorandom numbers during each run (unless the built-in interpreter or its RNG changed since 6G60).

**Comment by vlaviano** [comment]
angstsmurf wrote:
> I had a similar issue in the Arbot Maps & Antiques shop, where the parser insisted on examining the room rather than the map collection.

Yeah, that makes sense, since the local looking grammar line for examine is placed before the regular one.

**Comment by vlaviano** [comment]
More on the trace:

The two matched objects that are producing the MULTI_PE error for line 2 are:
Reclamation security (6224269) in nothing : 2136 points
The password (6264269) in ourselves : 2176 points

Counterfeit Monkey defines reclamation security like this:
```
The reclamation computer is running a password lock program called reclamation security.
```
Presumably, the word "password" matches reclamation security because of the name of its kind, password lock program, which is defined in the Computers extension. (The Computers extension also defines password as a text property of a password lock program, which is why the password in the game itself has to be called password-thing.)

I can reproduce this issue with the following test program.
```
Include Computers by Emily Short.

Lab is a room.

A kewl computer is a computer in the Lab.
The kewl computer runs a password lock program called kewl security.
The password of kewl security is "i7iskewl".

The password-thing is a thing. The printed name is "password".
Understand "password" as the password-thing.
The player carries the password-thing.

Test me with "x password / turn on computer / x password".
```
When the computer is turned on, the screen is examined, which causes the currently running program (called the controlling program) to be made part of the screen and thus placed into scope:
```
Chapter 3 - Which Program Receives Input?

To decide what object is the controlling program of (chosen computer - a computer):
	let the chosen screen be a random screen that is part of the chosen computer;
	repeat with item running through software which is part of chosen screen:
		remove item from play; 
	if the chosen computer runs no software:
		decide on nothing;
	otherwise:
		let the chosen program be the fiercest software run by the chosen computer;
		now the chosen program is part of the chosen screen;
		decide on the chosen program. 
```
So, this explains why reclamation security is a candidate for matching. The remaining question is why 2176 points doesn't trump 2136 points during adjudication and produce a clear winner instead of a MULTI_PE error.

**Comment by angstsmurf** [comment]
Another mystery is why "does the player mean" rules won't add or remove a single point from those scores. Or maybe I'm just writing them wrong:

```
Does the player mean examining the password-thing:
	it is very likely.

Does the player mean examining reclamation security:
	it is very unlikely.
```

**Comment by vlaviano** [comment]
This part of the infamous "indef plural" code in Adjudicate is responsible for rejecting the input:
```
    if (indef_mode == 1 && indef_type & PLURAL_BIT ~= 0) {
        if (context ~= MULTI_TOKEN or MULTIHELD_TOKEN or MULTIEXCEPT_TOKEN
                     or MULTIINSIDE_TOKEN) {
            etype = MULTI_PE;
            return -1;
        }
```
indef_type has PLURAL_BIT set, but the token that we're matching (NOUN_TOKEN) isn't one that can represent multiple objects.

So... why are we in indef_mode and why is PLURAL_BIT set? It wasn't the case when NounDomain was first called, but it was true by the time that Adjudicate was called.

This seems to be set in TryGivenObject, part of searching through objects in scope during NounDomain, when it matches a plural word:
```
            if (dict_flags_of_noun & 4) {
                if (~~allow_plurals) k = 0;
                else {
                    if (indef_mode == 0) {
                        indef_mode = 1; indef_type = 0; indef_wanted = 0;
                    }
                    indef_type = indef_type | PLURAL_BIT;
                    if (indef_wanted == 0) indef_wanted = INDEF_ALL_WANTED;
                }
            }
```
So some word is plural. Which one?

I compiled my test program to z8 and ran it through infodump (part of ztools) with the -d and -c 1 options set to dump out dictionary info:
```
$ ~/IF/Programming/ztools731/infodump -d -c 1 output.z8 > output.dump
$ grep plural output.dump
[  45] @ $9c54 computers [84 00 00] <noun> <plural>
[ 127] @ $9f36 keyboards [84 00 00] <noun> <plural>
[ 139] @ $9fa2 lock      [c5 ce 00] <noun> <plural> <verb>
[ 181] @ $a11c password  [84 00 00] <noun> <plural>
[ 189] @ $a164 programs  [84 00 00] <noun> <plural>
[ 210] @ $a221 rooms     [84 00 00] <noun> <plural>
[ 223] @ $a296 screens   [84 00 00] <noun> <plural>
[ 256] @ $a3bf softwares [84 00 00] <noun> <plural>
[ 284] @ $a4bb things    [84 00 00] <noun> <plural>
```
So, hmm, the word "password" is flagged in the dictionary as plural. I suspect that this is an artifact of the Computers extension.

Looking at the generated I6 code, we see that the password lock program (kewl_security in my test program) is defined like this:
```
Object I147_kewl_security ""
    class K28_password_lock_program
...
    with name 'kewl' 'security' 'password//p' 'lock//p' 'programs//p' 'software' 'desktop' 
...
;
```
and this is where the dictionary word 'password' gets it plural flag (//p).

Looking at the definition of the password lock program kind (I6 class), we see:
```
Class K28_password_lock_program 
    class K26_software
    with plural BC_160
...
;
...
Array BC_160 --> PACKED_TEXT_STORAGE TX_PS_31;
...
Constant TX_PS_31 = "password lock programs";
```
So my thought here is that, because the password lock program kind has a plural of "password lock programs", each of those individual words was marked plural, even though only "programs" really ought to be.

However, I tested this hypothesis by defining an email program as well, and, even though the plural of the email program kind is "email programs", the instance of that kind had a name property that looked like:
```
Object I148_kewl_email ""
    class K31_email_program
...
    with name 'kewl' 'email'  'programs//p' 'software' 'desktop' 
```
We can see that 'email' remains singular and only 'programs' is flagged plural. So there's something special about password lock programs.

**Comment by vlaviano** [comment]
More experimentation:
```
Test Chamber is a room.

A very cool weapon is a kind of thing.
The sword is a very cool weapon in Test Chamber.
```
Produces:
```
Object -> I127_sword ""
    class K16_very_cool_weapon
...
    with name 'sword' 'very//p' 'cool//p' 'weapons//p' 
...
;
```
So it looks like a blanket I7 issue rather than something specific to the Computers extension. I've tried this with "very truly cool weapon" and "cool weapon" as kinds, and *both* of them pluralize all words in the plural name of the kind, so now 'email' is the unusual word in that it isn't pluralized. I've also tried "awesome weapon" thinking that email beginning with a vowel and having article 'an' might matter, but 'awesome' is also flagged plural in the sword's name property.

**Comment by vlaviano** [comment]
A possible fix for the immediate issue here is to rename "password lock program" in Computers to "password-lock program". This should create 'password-lock//p' (truncated) instead of 'password//p' and 'lock//p', which seems less likely to interfere with anything else.

**Comment by angstsmurf** [comment]
That seems to do it. Excellent work!

**Comment by curiousdannii** [comment]
This seems very odd. Should it be reported as an Inform bug?

**Comment by vlaviano** [comment]
Probably. It depends on whether it was intended that all words in an object's plural name be flagged as plural in the dictionary. I personally think that, even if intended, it's broken. This comes out of automating something in I7 (flagging dict words as plural) that used to be done in I6 manually by the author. It was also possible in I6 to refrain from flagging a word plural and instead write parse_name routines that would treat a word as plural or not in a context dependent way. See the example at the end of §29 in the DM4.

It seems like, if we're going to stick with automating it, we'd get better results by only flagging the final word in a multi-word plural. It would break on stuff like "brothers in law", but overall would be correct more often. If the Conway pluralization algorithm referenced in §4.4 allows us to efficiently compute the predicate IsPlural(word), we could do even better and flag only those words in the plural name of an object that actually are plural.

This is a good simple test program that illustrates the issue:
```
Test Chamber is a room.

A shiny treasure is a kind of thing.
The shiny coin is a shiny treasure in Test Chamber.
The gold watch is a shiny treasure in Test Chamber.

Test me with "get treasures / x shiny".
```
Looking at the I6 code for this program clarified what was happening with 'email' in my earlier example.
I called my instance of email program "kewl email" and the plurality of the word 'email' in the name of the instance overrode the plurality of the word 'email' in the name of its kind when creating the name property of the instance. If I instead name the instance "kewl messages", then I get 'email//p' 'programs//p' in its name property. This doesn't help us much, since it just takes a single instance of 'foo//p' to flag 'foo' plural in the dictionary, which causes the word to be treated as plural throughout the program (as with 'shiny' in the test program).

**Comment by angstsmurf** [comment]
So is there an obvious explanation why this will give an error rather than asking the player to disambiguate?

**Comment by vlaviano** [comment]
It doesn't disambiguate, because 'password' is flagged as plural in the game's dictionary. A plural word is allowed to refer to multiple objects, so, at the level of matching objects to noun phrases, there's no need to disambiguate which single object is meant. 

It gives an error, because the grammar for the verb that we're trying to use (examine) has a noun token for the direct object, and, at the level of parsing grammar lines, a noun token is only allowed to match a single object.

These two statements make sense in isolation, but not so much when taken together. It seems as though the parser's knowledge that it's trying to match a noun token should preclude it from accepting a group of objects referred to by a plural word without disambiguation, but it doesn't.

Consider the following test program:
```
Test Chamber is a room.

A silver coin is a thing in Test Chamber.
A gold coin is a thing in Test Chamber.
Understand "coins" as the plural of silver coin.
Understand "coins" as the plural of gold coin.

Test me with "take coins / drop coin / gold / x coins".
```
If we type "take coin", the parser needs to disambiguate. If we type "take coins", it doesn't, because the plural word 'coins' can refer to both coins at once. If we type "x coins", we're told that multiple objects can't be used with that verb; we're not asked which coin we want to examine.

**Comment by angstsmurf** [comment]
This turns out to be such a common and annoying problem in this game that I think it might be a good idea to modify the script that inserts letter hash codes into the I6 code to remove any unwanted plural tokens as well.

**Comment by vlaviano** [comment]
How will you determine which plural words are unwanted?

**Comment by angstsmurf** [comment]
That is a good question. Of course we won't know until they start causing trouble and we see them in the i6 source. And then again we can't be sure that removing them won't cause trouble somewhere else.

**Comment by curiousdannii** [comment]
I definitely think this should be reported to the Inform 7 bugtracker, but I'm still not clear on the details myself. Can one of you do so?

**Comment by vlaviano** [comment]
http://inform7.com/mantis/view.php?id=1920

**Comment by angstsmurf** [comment]
> These two statements make sense in isolation, but not so much when taken together. It seems as though the parser's knowledge that it's trying to match a noun token should preclude it from accepting a group of objects referred to by a plural word without disambiguation, but it doesn't.

I suppose this is a related but separate issue. Perhaps we should open a bug report / feature request for that too?

**Comment by vlaviano** [comment]
> To the parser it seems that none of the grammar lines for examine fits the input, so it just gives the error message of the last one it tried.

Not the last one it tried, the one that produced the most interesting (highest-numbered) error message.

**Comment by vlaviano** [comment]
> So is there a solution to this?

I think so, but we need to formulate the problem in a productive way so that we're not saying "rewrite the entire parser, please." I think that we could look at allow_plurals, which is used during descriptor parsing to provisionally put the parser into indef plural mode on the first of two passes when an ambiguous number is encountered. It's always initialized to true the first time through, but perhaps we could set it to false for certain token types.

**Comment by angstsmurf** [comment]
> The error message makes sense for _that grammar line_.

Just to clarify my reasoning above (to myself as much as to you): in this case "You can't use multiple objects with that verb" also makes sense for that grammar line. The parser thinks that I want to do something to multiple nouns, and the grammar line for local looking only accepts one single (locally-present) room. So I was thinking that in those cases, when a scope routine only accepts a single object and the parser is trying to match multiple objects, it would always be more informative to say "You can't use multiple objects" rather than "noun did not make sense in context". But as you have explained, that might not always be the case. I was thinking of something like a check in the routine that prints the final error message, but I realize now how much added complexity that would take.

I'm afraid I don't quite follow your suggestion. Do you mean that we should set allow_plurals to false in the the code that checks for locally-present room? I experimented with doing that, but it didn't seem to have any effect.

**Comment by vlaviano** [comment]
Sure, they both make sense. The question is which is more significant: 'not a room when looking for a room' or 'plural when looking for singular'. It's arguable, but the parser currently considers the former to be more significant and worthy of being reported.

My suggestion was that the parser code should set allow_plurals to false for tokens that can't accept multiple objects. This would be in ParseToken__, part of Parser.i6t.

**Comment by angstsmurf** [comment]
All right, I wasn't sure if you meant that this was something we should do in the Counterfeit Monkey code or if it was a proposed library change. So it would be a suggestion to Graham Nelson then? Or to David Griffith?

**Comment by vlaviano** [comment]
Yeah, it was an I7 suggestion, not a Counterfeit Monkey suggestion.

**Comment by curiousdannii** [comment]
If we can patch the parser in a generally applicable way then we can make a patches extension (like [we have before](https://github.com/i7/extensions/tree/master/Friends%20of%20I7)) and link to it in the bug report. This will help anyone else who runs into the bug, and Graham will probably adopt the patch as well, as he has previously.
