### ISSUE TITLE
ACHIEVEMENTS should print unreached achievements

### ISSUE THREAD

**Issue by dfabulich** [i7/counterfeit-monkey#151]
At the end of the game, you're prompted to use the ACHIEVEMENTS command to review the achievements you've reached so far. But that's basically what the SCORE command does. Instead, ACHIEVEMENTS should print the achievements that you haven't reached, so players can learn what puzzles are available, and the SCORE command should be available at end game so you can see what you _did_ accomplish.

**Comment by angstsmurf** [comment]
I implemented this with 7be754f, but it is not ideal. It is very inefficient, making full-text comparison between two tables, and there is a noticeable pause when listing the achievements, at least in the IDE. 

A new achievement is awarded for getting all the achievements, the "Atlantida award for accomplishing every possible achievement", but because the achievements are listed alphabetically, it comes second or third after Alex and Andra, which feels kind of wrong. Perhaps it should just be renamed to something starting with a double AA or Z.

Also, the ACHIEVEMENTS command will be listed in the final question options whether you have all the achievements or not. It would be more elegant to just remove it if you have them all, but I don't know how to do it. I tried blanking out the row of the table, but that caused errors.

I added three new commands to help testing this: ACCOMPLISH ACHIEVEMENTS to get all of them, END STORY and END STORY FINALLY to simulate dying or winning. To reset all achievements, just delete the monkeyac file.

**Comment by angstsmurf** [comment]
I guess this does qualify as fixed now.

**Comment by angstsmurf** [comment]
While we have you here, @emshortif, perhaps you have an opinion on this as well?

**Comment by emshortif** [comment]
Not really. I can only vaguely reconstruct why I didn't tell the player all the available achievements back in the day, but I think it was because some of them are a real pain to figure out on your own, and I meant them more as fun easter eggs than as aspirations for the player. The ones I thought would be worth drawing the player's attention to, I did with e.g. the score tracking which letters you still haven't removed. But if there's a desire for this functionality, I also don't have strong feelings against.
