### ISSUE TITLE
Disambiguation bug asking about Altantida

### ISSUE THREAD

**Issue by eakst7** [i7/counterfeit-monkey#155]
I looked up 1983 in the filing cabinet and found a reference to Atlantida.  I tried `ask about atlantida` (not sure whom I was asking...I guess I was asking my "Alex" self) and got the following:

```
>l
Oracle Project
This is nothing less than the command center for a massive propaganda campaign. Paintings of Atlantida and polling charts cover the walls, dating back to the second world war and continuing straight through to the present.
 
A filing cabinet stands in the corner. It is on a long table, alongside a weight and a paper. 
 
You can go south to Wonderland and east from here.
 
>look up 1983 in filing cabinet
This year's folder doesn't contain any official propaganda posters; instead it's bulging with copies of a protest leaflet that shows a bare-breasted Atlantida leading rebels against the Bureau of Orthography, carrying placards in favor of more referenda and true individual liberty.
 
>ask about atlantida
Who do you mean, 1) Atlantida or 2) Atlantida?
 
>1
I didn't understand that number.
```

(Same error if I respond `2`, btw...)

**Comment by angstsmurf** [comment]
Thanks for reporting this!

It was actually two separate bugs. The first one, asking about which Atlantida you mean, should be taken care of by a825ba2. The second one, printing a nonsensical error message, should be fixed by 663d9ca.

This would manifest any time in the game you asked about someone not present, when it triggered a "Who do you mean" question and you were not actually talking to somebody.
