### ISSUE TITLE
Can't get past Atlantida without attracting the guards - possible timing bug?

### ISSUE THREAD

**Issue by creatrixtiara** [i7/counterfeit-monkey#169]
Hi there,

I'm at the point where I've met Atlantida for the first time and I'm trying to escape her. I tried just about everything, then after looking up walkthroughs and source codes I learn that the answer is to shoot the gel rifle with the anagram gun, then use the gel on the astrologer. However, no matter how many times I do this, before I can do anything to the astrologer the guards come and arrest me. I am stuck on a loop. 

Scouring through the repo again, I find this code which might be causing problems:

"Waiting for guards ends in capture when the time since waiting for guards began is greater than 1 minute."

It did take me more than one minute to work out what to do, yes. However, even when I start that scene again (after getting the "wouldn't this be foolish" message), the timer doesn't seem to reset. I have UNDO'd as far back as possible but it doesn't help. Restoring my save file doesn't help really. My only option right now seems to be to reset the game from the beginning, which seems harsh.

I am playing this on ipayif via Google Chrome on Windows 10.

**Comment by angstsmurf** [comment]
I'm sorry, but there isn't a lot I can do. In a way, it works as intended: answering YES to the "Shall we suppose we didn't?" question after dying will trigger an UNDO. It will only ever rewind the game one turn.

It would be quite a bit of work to make it really get the player out of unwinnable situations, and even if this is implemented in a future version, your save will not be compatible.

If you really do not want to restart the game and you don't have any earlier saves, the best I can offer is that you run a debug build and skip ahead to the end. In the build [here](https://tass.neocities.org/play.html), just type TEST ACT1 and wait a couple of minutes. It will look as if the game has crashed, but it really is still running, just not showing any text. When it is finished, type TEST ACT2 and so on until TEST ACT4. After act 4, type TEST DADCHAT and then TEST MEETA. That should bring you roughly to where you were. Sorry for the inconvenience.

**Comment by dfabulich** [comment]
FWIW, I can't reproduce this bug, but you didn't mention which interpreter you're using; the `undo` capacity is dependent on the interpreter.

I've attached a save from Release 9 immediately before entering the personal apartment. (`go east` to enter the apartment.)

If you enter the apartment and `wait` six times, you'll lose; the game will end, saying, "shall we suppose we didn't?" To survive at this point, you can type:

```
yes
undo
undo
undo
undo
shoot the rifle
wait
gel the astrologer
get the rifle
shoot atlantida with rifle
```

And you're good. You _do_ need to manually `undo` a few times, but on Lectrote, the `undo` stack is ten deep, and on Spatterlight it's seven deep, which is still more turns than you can even _survive_ in Atlantida's presence, so you're fine.

If four is too many, you can actually get by with as few as two manual `undo` actions.

```
yes
undo
undo
shoot the rifle
wait
gel the astrologer
shoot atlantida with rifle
```


[battle.glksave.zip](https://github.com/i7/counterfeit-monkey/files/5080005/battle.glksave.zip)

**Comment by creatrixtiara** [comment]
I did mention it in my original post but I seem to have misspelled it - I was playing it on [IPlayIf](http://iplayif.com/?story=https%3A%2F%2Fgithub.com%2Fi7%2Fcounterfeit-monkey%2Freleases%2Fdownload%2Fr9%2FCounterfeitMonkey-9.gblorb) which if I'm reading correctly uses Parchment.

I UNDO-ed as far as it'd let me (until I got the UNDO is exhausted message) but I still got the immediate-guards issue. I had thought that saying "yes" after "foolish choice" would reset the scene, which includes resetting the timer, but admittedly I am basing this on playing other games in other formats where that's what tends to happen, rather than interactive fiction/text adventure per se.

**Comment by dfabulich** [comment]
On what browser? I just quickly played through the game at the link you provided in Chrome 84 for macOS Catalina 10.15.5, and did the same test I described above: enter the personal apartment, wait six times, "y" to undo, then undo four more times, then do the right thing to solve the puzzle. It just worked.

**Comment by creatrixtiara** [comment]
Chrome on Windows 10. I'm not sure why it's not working for me?

**Comment by creatrixtiara** [comment]
Looking at some of the source code, there seems to be something about Atlantida pressing a bell to call the guards, which triggers the 1 minute thing. However, whenever I start that scene again, that bell scene doesn't happen again. It seems to skip past that and perhaps assume the guards got called ages ago.

**Comment by angstsmurf** [comment]
There was an old bug, #3, that this should not be confused with. That happened because the "Shall we suppose we didn't?" mechanism wasn't using undo at all.

When multiple undos work, it is a pretty fail-safe way to get out of trouble in this game. Every undo contains a complete memory state of the game, and undoing four times will put the game in the exact state it was four turns ago.

However, there are plenty of reasons why multiple undos will not work. The complete game state of Counterfeit Monkey is huge (although we have done a lot to make it smaller) so many interpreters will only have space for one undo, and sometimes not even that. @curiousdannii wrote some excellent code that checks if the interpreter can store an undo, and if not, stores the undo state to a special file instead. But when you play in a browser, there may be very limited disk space allowed for writing external files, so you still may only get one undo or two.

Also, undo states are not included in save files, so if you save the game and quit, all undo states will be gone when you return later and restore.

Fortunately, there are few death situations in this game that you actually need more than the single "Shall we suppose we didn't?" undo to get out of. This one is actually the only one I know of, although it seems likely there are more. The best solution would probably be some kludge that makes "cheating death" do more than just undo in this case. Unfortunately, you will still have to restart. But then at least the same thing won't happen to others.

**Comment by angstsmurf** [comment]
I wrote some code that creates a save file when the Atlantida confrontation begins, and restores from that instead of undoing if the game detects that the player is in a situation that requires more than one undo to get out of.
