### ISSUE TITLE
Possible stuck state in fight scene?

### ISSUE THREAD

**Issue by dbbnrl** [i7/counterfeit-monkey#173]
--- WARNING:  Very spoiler-y ---

.
.
.
.
.

I managed to get myself into a stuck state (meaning, I was forced to restore from an old save) during the final fight scene with Atlantida.

I had not yet shot the gel rifle, and the guards were on their way.  I reached a state where I had exactly one move left before the guards burst in and end the game.  At that point, although shooting the rifle does work (i.e., the astrologer appears), that action uses up my one remaining move and the game ends.  After the undo, I'm stuck in the same situation -- there is no single-turn action that can save me, and the undo only goes back one turn.

This was easily resolved by shooting the rifle earlier in the sequence.

I apologize if I'm just missing something -- please close this issue if the answer is that I just haven't come up with the correct clever solution.

**Comment by angstsmurf** [comment]
This is the same issue as #169, and is fixed in the repository code with a special save file created automatically for this scene only. That is no consolation for you or others in you situation, so I suppose it is time for a new release.

It is surprising that there are several reports in a row of people getting stuck here in the latest version, as this scene has always worked this way, as far as I can tell, and nobody ever reported it before.

**Comment by dbbnrl** [comment]
Ah, sorry for the duplicate.  I did look through open issues, but didn't search closed ones.

**Comment by angstsmurf** [comment]
I'm sorry for not getting a fixed release out earlier.

**Comment by angstsmurf** [comment]
Fixed (I hope) in release 10.
