### ISSUE TITLE
Color issue on Lectrote and Firefox

### ISSUE THREAD

**Issue by angstsmurf** [i7/counterfeit-monkey#63]
With the latest fixes, Lectrote shows some padding below the map in a slightly darker shade of blue. There has always been a similar issue in Firefox, with darker fields on both sides of the map. Obviously this is due to how these browsers manage color (Lectrote uses Chromium, right?).

If this happens because the map is a bitmap image and the filler space is not, could we perhaps instead use a blue bitmap image for the padding, stretched appropriately?

Firefox:
<img width="751" alt="skarmavbild 2016-10-04 kl 08 27 02" src="https://cloud.githubusercontent.com/assets/5066755/19064281/9699f3b2-8a0c-11e6-93fb-dbcc18b64907.png">

Lectrote:
<img width="789" alt="skarmavbild 2016-10-04 kl 08 02 37" src="https://cloud.githubusercontent.com/assets/5066755/19064284/9b81c27e-8a0c-11e6-8857-df1d5acb3cb0.png">

**Comment by curiousdannii** [comment]
I noticed this in the windows IDE too. I think the problem is the gamma of the PNGs. It's probably worth raising a Quixe bug, but I suspect the answer might be won't-fix.. 

Replacing it with a stretched image would work well I imagine. Even if the terps get fixed that would probably be worth doing. 

Alternatively we could see if we can remove the gamma info from the images.

**Comment by curiousdannii** [comment]
@erkyrath I'd appreciate your thoughts on how PNGs with gAMA chunks are theoretically meant to be displayed in Glk. Should we be able to paint in the background with the same RGB value and have it appear seamless?

**Comment by curiousdannii** [comment]
My tests (all on Windows 10)

Interpreter | Image colour | Background colour
-------------|----------------|------------
Windows-Glk | `007ADF` | `007ADF`
Garglk | `0078DD` | `007ADF`
Lectrote | `008BE4` | `007ADF`
Quixe (Chrome and Firefox) | | `007ADF`

But note that @angstsmurf's screenshots have other different colours too...

**Comment by erkyrath** [comment]
I sense that if I stick my hand into the color-display-profile blender, I will not draw it back bearing a simple solution to the problem.  :(

(Color profile is not the same as gamma.)

Lectrote uses Chromium, yes.

**Comment by erkyrath** [comment]
If removing the gamma flag from the PNGs gives us a color match cross-platform (including Quixe on Safari/Chrome/Firefox), then I'll add that to the spec as a recommendation.

If it only fails in a few cases, well, let's see what they are...

(GIMP can remove this flag just by opening the PNG and then re-exporting it with "save gamma" turned off in the PNG options.)

**Comment by curiousdannii** [comment]
Oh, so you think the problem might be different colour profiles rather than gamma? Neither is really something I know much about.

I would guess that if we stripped the gamma and made the colour profile be the normal sRGB that it would show the same in all interpreters, but as the darker colour. If we used a stretched image instead of painting rectangles then hopefully it would be seamless in the lighter colour, but it wouldn't be the same on all terps. I don't know if Emily was really caring too much about the colour, or if this was just the default of her image editor.

I'll make a test build with the gamma turned off for the first map location. And if I can see how to check the colour profile I'll make a second test build.

**Comment by erkyrath** [comment]
I looked at one of the PNG files and it only had gamma, not a profile. (According to MacOS Preview.app.) So I was wrong about profile being involved here, although it is a concern in general.

**Comment by curiousdannii** [comment]
[Counterfeit Monkey.zip](https://github.com/i7/counterfeit-monkey/files/527052/Counterfeit.Monkey.zip)

I removed the gamma chunk of the first map image. It fixes the problem in Lectrote but Gargoyle is unchanged. The Gargoyle colour difference is very subtle though, so maybe we just shouldn't bother. But I haven't tried stretching out a blue image instead of drawing a rectangle, so that might be an easy solution.

I suggested adding some guidelines to the specs: https://github.com/erkyrath/glk-dev/issues/4

**Comment by erkyrath** [comment]
> But I haven't yet tried stretching out a blue image instead of drawing a rectangle, so that might be an easy solution

I expect it will be.

**Comment by curiousdannii** [comment]
[Counterfeit Monkey background image.zip](https://github.com/i7/counterfeit-monkey/files/530798/Counterfeit.Monkey.background.image.zip)

It seems to work fine! :)

**Comment by angstsmurf** [comment]
Looks fine here, except for a new black line at the bottom of the map on Lectrote:

<img width="598" alt="skarmavbild 2016-10-15 kl 14 51 18" src="https://cloud.githubusercontent.com/assets/5066755/19410232/de21b4b2-92e6-11e6-9479-a2df14af577c.png">

**Comment by curiousdannii** [comment]
@angstsmurf Yep that's https://github.com/erkyrath/glkote/issues/12. It just wasn't visible before because the background colour was blue rather than black.

**Comment by angstsmurf** [comment]
Yes, fixed in [Lectrote 1.1.5](https://github.com/erkyrath/lectrote/releases). Excellent! I guess we can close this issue now.

**Comment by curiousdannii** [comment]
@angstsmurf The window padding is fixed, but I'm still not sure I've fixed the colour issues. I want to do a little more testing once I've finished some essays.

**Comment by angstsmurf** [comment]
Is this still relevant? I haven't seen any colour issues in a long time, but I haven't really played on anything but macOS.

**Comment by curiousdannii** [comment]
No idea sorry.

**Comment by angstsmurf** [comment]
Guess nobody will mind if I close this then.
