### ISSUE TITLE
Conversation bug

### ISSUE THREAD

**Issue by curiousdannii** [i7/counterfeit-monkey#65]
https://www.intfic.com/t/counterfeit-monkey-and-glulx-issues/320

**Comment by angstsmurf** [comment]
I've noticed before that quips sometimes get numbered wrong in disambiguation questions, and there is actually a commented, non-working  [attempt to fix it](https://github.com/i7/counterfeit-monkey/blob/f97c06e8a588a8407f32bad8b1c97bbe4a4b2451/Counterfeit%20Monkey.materials/Extensions/Emily%20Short/Threaded%20Conversation.i7x#L587) in Threaded Conversation.

**Comment by curiousdannii** [comment]
Excellent! But it still seems wrong that the quips with other numbers are even being considered...

**Comment by angstsmurf** [comment]
Well, it is #51 all over again, as discussed [here](http://www.intfiction.org/forum/viewtopic.php?f=7&t=20314). I'm not sure why the parser always seems to prefer the what the movie is quip to the when the movie starts quip, however.

**Comment by angstsmurf** [comment]
And also not why the old 'Does the player mean doing something when the player's command includes "[number]"' is not triggered when disambiguating quips.

**Comment by angstsmurf** [comment]
Or perhaps you were asking why we're only checking for the number "1" choice? It seems that "1" is the only choice that causes trouble, as long as the verb does not allow for multiple objects. But we can change it to check for "[number]" instead if it that turns out not to be the case. That will probably be slower, however.

**Comment by curiousdannii** [comment]
I'd forgotten the old bug report and discussion.
